function home(){
	var title = document.getElementsByClassName("title")[0];
	var text = document.getElementsByClassName("text")[0];
	var citation = document.getElementsByClassName("citation-text")[0];
	title.innerHTML = "Home";
	text.innerHTML = "School is the fundament of society; it conceives a foundation of the knowledge youth would need to know regarding the modern world and aids in finding and developing interests. Considering the vast importance of knowledge and getting through life in the best way possible, it has become a norm to attend school or get an education, as anything otherwise would be looked down upon.<br><br>However, it is common for the general purpose and function of the modern education system to be overlooked and assumed is the best for the youth, which begs the question of whether the current system really works or not. Criticism is not uncommon for the method students learn through schooling, with a prime example being Albert Einstein’s famous quotation in which he stated, <div class = 'quotation'>“Education is what remains after one has forgotten what one has learned from school,” <a class = 'cite' href = 'https://files.eric.ed.gov/fulltext/EJ1076383.pdf' target = '_blank'>[1]</a></div> which nods to the fact that what is learned in school is often forgotten after a very short period of time.<br><br>Considering the controversy surrounding the modern education system, we should take a step back and consider how we are teaching our youth and what changes could be made to develop our understanding of the world while utilizing the best methods to do so, rather than just continuing with what we had been doing since the ancient Sumerians. ";
	citation.innerHTML = "<div class = 'citation-column'>[1]</div><a href = 'https://files.eric.ed.gov/fulltext/EJ1076383.pdf' target = '_blank'>https://files.eric.ed.gov/fulltext/EJ1076383.pdf</a><br>p. 34";
}

function current_sys(){
	var title = document.getElementsByClassName("title")[0];
	var text = document.getElementsByClassName("text")[0];
	var citation = document.getElementsByClassName("citation-text")[0];
	title.innerHTML = "Current Educational System";
	text.innerHTML = "Within the book <i>Constructivist Teacher Education</i>, Jennifer A. Vadeboncoeur goes into how education systems generally revolve around two fundamental views in which she states, <div class = 'quotation'>“Throughout the twentieth century, two competing views of child development and the purpose of education have framed the teaching of pedagogy in teacher education. In the first view, the purpose of education is to educate the individual child in a manner which supports the child’s interests and needs…In the second view, the purpose of education is social transformation and the reconstruction of society aligned with democratic ideals.” <a class = 'cite' href = 'https://www.taylorfrancis.com/books/e/9780203973684/chapters/10.4324/9780203973684-9' target = '_blank'>[2]</a></div>These views are generally the basis most education systems rely on in modern schooling and shape the way youth are educated of the world. Specifically in public schools, the structure of how youth are taught typically follows the second view, with a norm having been set to how this structure plays out. This norm is as follows: <br><br>1) A teacher teaches a lesson to a group of students on a subject indicated within the curriculum provided by the provincial government. <br><br>2) Following the lesson(s), the students are assigned an assignment, worksheet, etc. which relates to the information taught in the lesson(s), allowing them to practice any new concepts. This assignment is often taken in for marks which reflects on the student’s overall performance in the class. <br><br>3) After repeating this process a given number of times, a standardized test is given to the students in which they are expected to answer a large amount of questions related to the past lessons on that subject matter. The purpose of this test is to evaluate the current level of the student and indicate whether they had pertained the knowledge taught to them and will reflect on their overall mark as well. <br><br>4) In some situations, a final exam is given to the students where they must answer an even greater amount of questions regarding everything they had been taught throughout the year, as to show the capability of the student as opposed to the beginning of the year.<br><br>The process indicated above is generally repeated throughout the span of twelve years, with additional years following in university or college. Throughout this process, students are expected to be taught information specified within the curriculum, which includes topic areas such as science, math, physical education, etc. This information is typically meant to provide youth with the most up-to-date and relevant information regarding each topic area as to allow for students to have the best and most accurate understanding of the modern world.";
	citation.innerHTML = "<div class = 'citation-column'>[2]</div><a href = 'https://www.taylorfrancis.com/books/e/9780203973684/chapters/10.4324/9780203973684-9' target = '_blank'>https://www.taylorfrancis.com/books/e/9780203973684/chapters/10.4324/9780203973684-9</a><br><i>Chapter 2<br>“Child Development and the Purpose of Education: A Historical Context for Constructivism in Teacher Education”<br> Written by Jennifer A. Vadeboncoeur</i>";
}

window.onload = function(){
	home();
}